/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankClass } from './bankClass';


/**
 * Embedded collection of Bank_class
 */
export interface EmbeddedCollectionBankClass { 
    /**
     * Resource collection
     */
    bankClasses: Array<BankClass>;
}
