/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Usergroup } from './usergroup';


/**
 * Embedded collection of Usergroup
 */
export interface EmbeddedCollectionUsergroup { 
    /**
     * Resource collection
     */
    usergroups: Array<Usergroup>;
}
