/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';


export interface EntityModelFactureRec { 
    amount?: number;
    dateLimReglement?: Date;
    datec?: Date;
    entity?: number;
    frequency?: string;
    lastGen?: string;
    links?: Links;
    localtax1?: number;
    localtax2?: number;
    note?: string;
    notePublic?: string;
    remise?: number;
    remiseAbsolue?: number;
    remisePercent?: number;
    rowid?: number;
    titre?: string;
    total?: number;
    totalTtc?: number;
    tva?: number;
}
