/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';


export interface EntityModelBankAccount { 
    accountNumber?: string;
    adresseProprio?: string;
    bank?: string;
    bic?: string;
    cleIban?: string;
    cleRib?: string;
    clos?: number;
    codeBanque?: string;
    codeGuichet?: string;
    comment?: string;
    countryIban?: string;
    courant?: number;
    currencyCode?: string;
    datec?: Date;
    domiciliation?: string;
    entity?: number;
    ibanPrefix?: string;
    label?: string;
    links?: Links;
    minAllowed?: number;
    minDesired?: number;
    number?: string;
    proprio?: string;
    rappro?: number;
    ref?: string;
    rowid?: number;
    tms?: Date;
    url?: string;
}
