/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Links } from './links';


export interface EntityModelCommandeFournisseur { 
    amountHt?: number;
    dateCloture?: Date;
    dateCommande?: Date;
    dateValid?: Date;
    entity?: number;
    links?: Links;
    localtax1?: number;
    localtax2?: number;
    modelPdf?: string;
    note?: string;
    notePublic?: string;
    ref?: string;
    refSupplier?: string;
    remise?: number;
    remisePercent?: number;
    rowid?: number;
    source?: number;
    tms?: Date;
    totalHt?: number;
    totalTtc?: number;
    tva?: number;
}
