/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FactureFourn } from './factureFourn';
import { Product } from './product';


export interface FactureFournDet { 
    dateEnd?: Date;
    dateStart?: Date;
    description?: string;
    factureFourn?: FactureFourn;
    importKey?: string;
    label?: string;
    localtax1Tx?: number;
    localtax2Tx?: number;
    product?: Product;
    productType?: number;
    puHt?: number;
    puTtc?: number;
    qty?: number;
    ref?: string;
    rowid?: number;
    totalHt?: number;
    totalLocaltax1?: number;
    totalLocaltax2?: number;
    totalTtc?: number;
    tva?: number;
    tvaTx?: number;
}
