/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductPrice { 
    datePrice?: Date;
    localtax1Tx?: number;
    localtax2Tx?: number;
    price?: number;
    priceBaseType?: string;
    priceLevel?: number;
    priceMin?: number;
    priceMinTtc?: number;
    priceTtc?: number;
    product?: Product;
    recuperableonly?: number;
    rowid?: number;
    tms?: Date;
    tosell?: number;
    tvaTx?: number;
}
