/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UsergroupRights } from './usergroupRights';
import { UsergroupUser } from './usergroupUser';


export interface Usergroup { 
    datec?: Date;
    entity?: number;
    nom?: string;
    note?: string;
    rowid?: number;
    tms?: Date;
    usergroupRights?: Array<UsergroupRights>;
    usergroupUsers?: Array<UsergroupUser>;
}
