export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './bankAccountEntity.service';
import { BankAccountEntityService } from './bankAccountEntity.service';
export * from './bankCategEntity.service';
import { BankCategEntityService } from './bankCategEntity.service';
export * from './bankClassEntity.service';
import { BankClassEntityService } from './bankClassEntity.service';
export * from './bankEntity.service';
import { BankEntityService } from './bankEntity.service';
export * from './bankUrlEntity.service';
import { BankUrlEntityService } from './bankUrlEntity.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './canUserEntity.service';
import { CanUserEntityService } from './canUserEntity.service';
export * from './categorieAssociationEntity.service';
import { CategorieAssociationEntityService } from './categorieAssociationEntity.service';
export * from './categorieEntity.service';
import { CategorieEntityService } from './categorieEntity.service';
export * from './categorieFournisseurEntity.service';
import { CategorieFournisseurEntityService } from './categorieFournisseurEntity.service';
export * from './categorieMemberEntity.service';
import { CategorieMemberEntityService } from './categorieMemberEntity.service';
export * from './categorieProductEntity.service';
import { CategorieProductEntityService } from './categorieProductEntity.service';
export * from './categorieSocieteEntity.service';
import { CategorieSocieteEntityService } from './categorieSocieteEntity.service';
export * from './commandeEntity.service';
import { CommandeEntityService } from './commandeEntity.service';
export * from './commandeFournisseurEntity.service';
import { CommandeFournisseurEntityService } from './commandeFournisseurEntity.service';
export * from './commandeFournisseurLogEntity.service';
import { CommandeFournisseurLogEntityService } from './commandeFournisseurLogEntity.service';
export * from './commandeFournisseurdetEntity.service';
import { CommandeFournisseurdetEntityService } from './commandeFournisseurdetEntity.service';
export * from './commandedetEntity.service';
import { CommandedetEntityService } from './commandedetEntity.service';
export * from './cronjobEntity.service';
import { CronjobEntityService } from './cronjobEntity.service';
export * from './elementElementEntity.service';
import { ElementElementEntityService } from './elementElementEntity.service';
export * from './factureEntity.service';
import { FactureEntityService } from './factureEntity.service';
export * from './factureFournDetEntity.service';
import { FactureFournDetEntityService } from './factureFournDetEntity.service';
export * from './factureFournEntity.service';
import { FactureFournEntityService } from './factureFournEntity.service';
export * from './factureRecEntity.service';
import { FactureRecEntityService } from './factureRecEntity.service';
export * from './facturedetEntity.service';
import { FacturedetEntityService } from './facturedetEntity.service';
export * from './facturedetRecEntity.service';
import { FacturedetRecEntityService } from './facturedetRecEntity.service';
export * from './mailingCiblesEntity.service';
import { MailingCiblesEntityService } from './mailingCiblesEntity.service';
export * from './mailingEntity.service';
import { MailingEntityService } from './mailingEntity.service';
export * from './productBatchEntity.service';
import { ProductBatchEntityService } from './productBatchEntity.service';
export * from './productEntity.service';
import { ProductEntityService } from './productEntity.service';
export * from './productFournisseurPriceEntity.service';
import { ProductFournisseurPriceEntityService } from './productFournisseurPriceEntity.service';
export * from './productFournisseurPriceLogEntity.service';
import { ProductFournisseurPriceLogEntityService } from './productFournisseurPriceLogEntity.service';
export * from './productLotEntity.service';
import { ProductLotEntityService } from './productLotEntity.service';
export * from './productPriceEntity.service';
import { ProductPriceEntityService } from './productPriceEntity.service';
export * from './productStockEntity.service';
import { ProductStockEntityService } from './productStockEntity.service';
export * from './profileController.service';
import { ProfileControllerService } from './profileController.service';
export * from './rightsDefEntity.service';
import { RightsDefEntityService } from './rightsDefEntity.service';
export * from './roleEntity.service';
import { RoleEntityService } from './roleEntity.service';
export * from './testController.service';
import { TestControllerService } from './testController.service';
export * from './userEntity.service';
import { UserEntityService } from './userEntity.service';
export * from './userParamEntity.service';
import { UserParamEntityService } from './userParamEntity.service';
export * from './userRightsEntity.service';
import { UserRightsEntityService } from './userRightsEntity.service';
export * from './usergroupEntity.service';
import { UsergroupEntityService } from './usergroupEntity.service';
export * from './usergroupRightsEntity.service';
import { UsergroupRightsEntityService } from './usergroupRightsEntity.service';
export * from './usergroupUserEntity.service';
import { UsergroupUserEntityService } from './usergroupUserEntity.service';
export const APIS = [AuthControllerService, BankAccountEntityService, BankCategEntityService, BankClassEntityService, BankEntityService, BankUrlEntityService, BasicErrorControllerService, CanUserEntityService, CategorieAssociationEntityService, CategorieEntityService, CategorieFournisseurEntityService, CategorieMemberEntityService, CategorieProductEntityService, CategorieSocieteEntityService, CommandeEntityService, CommandeFournisseurEntityService, CommandeFournisseurLogEntityService, CommandeFournisseurdetEntityService, CommandedetEntityService, CronjobEntityService, ElementElementEntityService, FactureEntityService, FactureFournDetEntityService, FactureFournEntityService, FactureRecEntityService, FacturedetEntityService, FacturedetRecEntityService, MailingCiblesEntityService, MailingEntityService, ProductBatchEntityService, ProductEntityService, ProductFournisseurPriceEntityService, ProductFournisseurPriceLogEntityService, ProductLotEntityService, ProductPriceEntityService, ProductStockEntityService, ProfileControllerService, RightsDefEntityService, RoleEntityService, TestControllerService, UserEntityService, UserParamEntityService, UserRightsEntityService, UsergroupEntityService, UsergroupRightsEntityService, UsergroupUserEntityService];
